### PR TITLE
Remove trailing whitespace and make indentation consistent

### PR DESCRIPTION
**Pull request by ryansb**
Some places used tabs, others spaces. 

[Review on Reviewable](https://reviewable.io/reviews/designbyfront/the-goldilocks-approach/8)

### CODE REVIEW

**Comment by Qalthos** [comment]
Happy birthday, pull request :cake:

**Comment by ryansb** [comment]
Happy 2nd birthday! :cake:

**Comment by liam-middlebrook** [comment]
The big :two: :cake: :confetti_ball: :exclamation:

**Comment by mansam** [comment]
Happy 2nd birthday, little pull request!

**Pull request closed without merging**
